package com.mayqlzu.apphere;

public enum RequestCodes {
	PLACE_HOLDER,
	MEMBERS_FRAGMENT_TO_COLLECT_CONTACTS_FROM_SMS,
	MEMBERS_FRAGMENT_TO_PICK_MEMBERS_FROM_PHONEBOOK,
	COLLECT_CONTACTS_FROM_SMS_TO_FILTER_CANDIDATES
}
